# Generated by cpp11: do not edit by hand

cpp11_predict <- function(object, x, sparse_x, prediction_type, seed, n_thread, verbose) {
  .Call(`_literanger_cpp11_predict`, object, x, sparse_x, prediction_type, seed, n_thread, verbose)
}

cpp11_train <- function(x, y, sparse_x, case_weights, tree_type, n_tree, predictor_names, names_of_unordered, replace, sample_fraction, n_try, draw_predictor_weights, names_of_always_draw, split_rule, max_depth, min_split_n_sample, min_leaf_n_sample, response_weights, n_random_split, alpha, min_prop, seed, save_memory, n_thread, verbose) {
  .Call(`_literanger_cpp11_train`, x, y, sparse_x, case_weights, tree_type, n_tree, predictor_names, names_of_unordered, replace, sample_fraction, n_try, draw_predictor_weights, names_of_always_draw, split_rule, max_depth, min_split_n_sample, min_leaf_n_sample, response_weights, n_random_split, alpha, min_prop, seed, save_memory, n_thread, verbose)
}
